# Generated by Django 3.2.7 on 2021-10-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='eid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='famount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='error_count',
            field=models.IntegerField(),
        ),
    ]
