# Generated by Django 3.2.7 on 2021-10-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20211018_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['fname']},
        ),
    ]
