# Generated by Django 3.2.7 on 2021-10-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_alter_food_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='diet_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
