# Generated by Django 3.2.7 on 2021-10-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_alter_diet_diet_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='error_name',
        ),
        migrations.RemoveField(
            model_name='train',
            name='error_count',
        ),
        migrations.RemoveField(
            model_name='train',
            name='error_name',
        ),
    ]
