# Generated by Django 3.2.7 on 2021-11-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_alter_exercise_eid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['eid']},
        ),
    ]
