version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/backend
    expose:
      - 8000
    env_file:
      - ./.env.prod