version: '3'

services:
  backend:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/backend
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev