# Generated by Django 3.2.7 on 2021-10-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('uact', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('val', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uuid', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('upw', models.CharField(max_length=15)),
                ('uage', models.IntegerField(max_length=3)),
                ('usex', models.CharField(max_length=7)),
                ('uheight', models.FloatField()),
                ('uweight', models.FloatField()),
                ('urdc', models.FloatField()),
                ('uact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.activity')),
            ],
        ),
    ]
