# Generated by Django 3.2.7 on 2021-10-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uage',
            field=models.IntegerField(),
        ),
    ]
