# Generated by Django 3.2.7 on 2021-10-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20211018_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.activity', verbose_name='uact'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uage',
            field=models.IntegerField(verbose_name='uage'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uheight',
            field=models.FloatField(verbose_name='uheight'),
        ),
        migrations.AlterField(
            model_name='users',
            name='upw',
            field=models.CharField(max_length=15, verbose_name='upw'),
        ),
        migrations.AlterField(
            model_name='users',
            name='urdc',
            field=models.FloatField(verbose_name='urdc'),
        ),
        migrations.AlterField(
            model_name='users',
            name='usex',
            field=models.CharField(choices=[['F', '여성'], ['M', '남성 ']], max_length=1, verbose_name='usex'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uuid',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uweight',
            field=models.FloatField(verbose_name='uweight'),
        ),
    ]
